/** @type {import('next').NextConfig} */
const nextConfig = {
  async rewrites() {
    return [
      { source: "/comingSoon", destination: "/pages/comingSoon" },
      { source: "/services", destination: "/pages/services" },
      { source: "/contact", destination: "/pages/contactUs" },
      { source: "/about", destination: "/pages/aboutUs" },
      { source: "/who-we", destination: "/pages/whoWeAre" },
      { source: "/partners", destination: "/pages/partners" },
      { source: "/timeline", destination: "/pages/timeline" },
      { source: "/leader", destination: "/pages/leadershipTeam" },
      { source: "/partner-with-us", destination: "/pages/partnerWithUs" },
      { source: "/career", destination: "/pages/careers" },
      { source: "/award", destination: "/pages/award" },
      { source: "/news", destination: "/pages/news&press" },
      { source: "/privacy", destination: "/pages/privacy" },
      { source: "/events", destination: "/pages/events" },
      { source: "/singleEvent", destination: "/pages/singleEvent" },
      { source: "/blogs", destination: "/pages/blogs" },
      { source: "/singleBlog", destination: "/pages/singleBlog" },
      { source: "/personalizedUniversity", destination: "/pages/ServicesPages/personalizedUniversity" },
      { source: "/applicationAssistance", destination: "/pages/ServicesPages/applicationAssistance" },
      { source: "/aidGuidance", destination: "/pages/ServicesPages/aidGuidance" },
      { source: "/immigrationSupport", destination: "/pages/ServicesPages/immigrationSupport" },
      { source: "/travelAssistance", destination: "/pages/ServicesPages/travelAssistance" },
      { source: "/postGraduationAid", destination: "/pages/ServicesPages/postGraduationAid" },
      { source: "/admissionProcess", destination: "/pages/ServicesPages/admissionProcess" },
      { source: "/studentGuidance", destination: "/pages/ServicesPages/studentGuidance" },
      { source: "/globalNetwork", destination: "/pages/ServicesPages/globalNetwork" },
      { source: "/studentSuccess", destination: "/pages/ServicesPages/studentSuccess" },
      { source: "/recruitmentSupport", destination: "/pages/ServicesPages/recruitmentSupport" },
      { source: "/collaboration", destination: "/pages/ServicesPages/collaboration" },
      { source: "/logIn", destination: "/pages/logIn" },
      { source: "/registration", destination: "/pages/registration" },
      { source: "/study-destinations", destination: "/pages/study-destinations" },
      { source: "/study-destinations/study-in-the-uk", destination: "/pages/study-destinations/UK" },
      { source: "/study-destinations/study-in-the-usa", destination: "/pages/study-destinations/USA" },
      { source: "/study-destinations/study-in-the-australia", destination: "/pages/study-destinations/Australia", },
      { source: "/study-destinations/study-in-the-canada", destination: "/pages/study-destinations/Canada" },
      { source: "/study-destinations/study-in-the-germany", destination: "/pages/study-destinations/Germany" },
      { source: "/study-destinations/study-in-the-new-zealand", destination: "/pages/study-destinations/NewZealand", },
      { source: "/study-destinations/study-in-the-uae", destination: "/pages/study-destinations/UAE" },
      { source: "/study-destinations/study-in-the-georgia", destination: "/pages/study-destinations/Georgia" },
      { source: "/study-destinations/study-in-the-finland", destination: "/pages/study-destinations/Finland" },
      { source: "/study-destinations/study-in-the-cyprus", destination: "/pages/study-destinations/Cyprus" },
      { source: "/study-destinations/study-in-the-switzerland", destination: "/pages/study-destinations/Switzerland", },
      { source: "/study-destinations/study-in-the-france", destination: "/pages/study-destinations/France" },
      { source: "/study-destinations/study-in-the-west-indies", destination: "/pages/study-destinations/West-Indies", },
      { source: "/singleUniversity/:Name", destination: "/pages/singleUniversity/:Name", }
    ];
  },
  images: {
    domains: ["i.ibb.co", "i.ibb.co.com"],
    unoptimized: true,
  },
};

export default nextConfig;
