import type { Metadata } from "next";
import "./globals.css";
import Navbar2 from "@/_components/shared/Navbar/Navbar";
import Footer from "@/_components/shared/Footer/Footer/Footer";
import Providers from "@/_components/QueryClientProvider/Providers";
import Chats from "@/_components/Chats/Chats";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { MyContextProvider } from "@/_components/Context/MyContextProvider";

export const metadata: Metadata = {
  title: "Shabuj Global Education",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={` antialiased`}>
        <Providers>
          <MyContextProvider>
            <ToastContainer />
            <Navbar2 />
            <div className="pb-10">
              {children}
              <Chats />
            </div>
            <Footer />
          </MyContextProvider>
        </Providers>
      </body>
    </html>
  );
}
